### ISSUE TITLE
Flownet Weights

### ISSUE THREAD

**Issue by DFStewart** [isarlab-department-engineering/LSVO#2]
Thanks for sharing code, I really enjoyed your paper. 

I've been trying to recreate your result, but I am having difficulty recreating the optical flow outputs you provide. Did you just resize the images and pass them through Flownet2 with the default weights or was it one of the earlier models?

**Comment by gabrielecostante** [comment]
Thanks for your interest. For this paper we used the earlier version of Flownet with the default weights (not the more recent Flownet2). The images are resized before feeding them into Flownet.
